In [2]:
from tensorflow.keras.preprocessing.text import one_hot

c:\Users\prita\OneDrive\Pictures\Desktop\DEEP LEARNING NLP\pritam\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1896, 4215, 5947, 4809],
 [1896, 4215, 5947, 2366],
 [1896, 3815, 5947, 3265],
 [6524, 2105, 7859, 1494, 3549],
 [6524, 2105, 7859, 1494, 2310],
 [7218, 1896, 9915, 5947, 1468],
 [957, 804, 5321, 1494]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1896 4215 5947 4809]
 [   0    0    0    0 1896 4215 5947 2366]
 [   0    0    0    0 1896 3815 5947 3265]
 [   0    0    0 6524 2105 7859 1494 3549]
 [   0    0    0 6524 2105 7859 1494 2310]
 [   0    0    0 7218 1896 9915 5947 1468]
 [   0    0    0    0  957  804 5321 1494]]


In [11]:
## feature representation
dim=10

In [17]:
from keras.models import Sequential
from keras.layers import Embedding, Input

model=Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step


array([[[ 0.04168991, -0.01523455,  0.03799706,  0.00913489,
         -0.02528988,  0.04825951, -0.04967222, -0.00530278,
         -0.03295387,  0.01114728],
        [ 0.04168991, -0.01523455,  0.03799706,  0.00913489,
         -0.02528988,  0.04825951, -0.04967222, -0.00530278,
         -0.03295387,  0.01114728],
        [ 0.04168991, -0.01523455,  0.03799706,  0.00913489,
         -0.02528988,  0.04825951, -0.04967222, -0.00530278,
         -0.03295387,  0.01114728],
        [ 0.04168991, -0.01523455,  0.03799706,  0.00913489,
         -0.02528988,  0.04825951, -0.04967222, -0.00530278,
         -0.03295387,  0.01114728],
        [ 0.04741771, -0.01461879,  0.03487072, -0.01932877,
         -0.00267365, -0.03331979,  0.03113266,  0.00792837,
         -0.00387827,  0.00211727],
        [ 0.00350388, -0.00719001, -0.04161546,  0.04480273,
          0.04405885,  0.00221384,  0.04414544, -0.03269026,
          0.01264102, -0.03373011],
        [-0.02057251,  0.02471361, -0.02472838, -0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 1896, 4215, 5947, 4809], dtype=int32)

In [28]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step


array([[[ 0.04168991, -0.01523455,  0.03799706,  0.00913489,
         -0.02528988,  0.04825951, -0.04967222, -0.00530278,
         -0.03295387,  0.01114728],
        [ 0.04168991, -0.01523455,  0.03799706,  0.00913489,
         -0.02528988,  0.04825951, -0.04967222, -0.00530278,
         -0.03295387,  0.01114728],
        [ 0.04168991, -0.01523455,  0.03799706,  0.00913489,
         -0.02528988,  0.04825951, -0.04967222, -0.00530278,
         -0.03295387,  0.01114728],
        [ 0.04168991, -0.01523455,  0.03799706,  0.00913489,
         -0.02528988,  0.04825951, -0.04967222, -0.00530278,
         -0.03295387,  0.01114728],
        [ 0.04741771, -0.01461879,  0.03487072, -0.01932877,
         -0.00267365, -0.03331979,  0.03113266,  0.00792837,
         -0.00387827,  0.00211727],
        [ 0.00350388, -0.00719001, -0.04161546,  0.04480273,
          0.04405885,  0.00221384,  0.04414544, -0.03269026,
          0.01264102, -0.03373011],
        [-0.02057251,  0.02471361, -0.02472838, -0.0